# Generated by Django 3.1.7 on 2021-03-18 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0002_event_the_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category', field=models.CharField(max_length=40)
        ),
        migrations.AddField(
            model_name='event',
            name='color', field=models.CharField(max_length=40)
        ),
    ]
