# Generated by Django 3.1.7 on 2021-04-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Important', 'Important'), ('Tentative', 'Tentative'), ('Recurrent', 'Recurrent'), ('Normal', 'Normal')], default='NORMAL', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('dddddd', 'WHITE'), ('ff4444', 'RED'), ('44ff44', 'GREEN'), ('4444ff', 'BLUE')], default='WHITE', max_length=40),
        ),
    ]
