# Generated by Django 3.1.7 on 2021-04-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20210415_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gcal_id',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
